### ISSUE TITLE
The binding may throw exceptions when working with libzmq-5.0.0

### ISSUE THREAD

**Issue by zzxx-husky** [zzxx-husky/zeromq-scala-binding#1]
Exception in thread "Thread-22" org.zeromq.ZMQException: No such file or directory
at org.zeromq.ZMQ$Socket.raiseZMQException(ZeroMQLibrary.scala:663)
at org.zeromq.ZMQ$Socket.recv(ZeroMQLibrary.scala:594)
at ...

Try fixing.

**Comment by zzxx-husky** [comment]
My test ran very well on win7 using ZMQ-4.0.4 (that is, the test runs 10 times and shows nothing wrong). But it fails easily when running on Fedora using libzmq-5.0.0.

**Comment by zzxx-husky** [comment]
The libzmq-5.0.0 is compiled from ZMQ-4.1.4.

**Comment by zzxx-husky** [comment]
See my new branch, which supports for zmq-4.1.4:
https://github.com/zzxx-husky/zeromq-scala-binding/tree/zmq-4.1.4
